export const Data = {
  Free$Paid: ['Free & Paid', 'Free', 'Paid', 'Sale'],
  Compatible: ['All versions', '5.4', '5.0 - 5.3', '4.5 - 4.9', '4.0 - 4.4'],
  Categories: ['All Categories', 'Apparel & Clothing', 'Art & Photography', 'Books', 'Buisness', 'Cars', 'Computer', 'Crafts and hobbies', 'Education', 'Electronics', 'Entertainment', 'Equipment and Tools', 'Fitness', 'Flower', 'Food & Drink', 'Furniture & Interior', 'Gifts', 'Health & Beauty', 'Industrial', 'Jewelry & Accessories'],
  Contents: [
    {
      img: 'https://market.x-cart.com/var/images/template_images/286.418/Skins_list_image_632x924_8_7.jpg',
      MainImg: 'https://market.x-cart.com/var/images/product/680.580/Skin_details_image_1360x1160px_3_8.jpg',
      LogoImg: 'https://market.x-cart.com/var/images/module_icons/120.60/icon_188.png',
      head: 'Kitchen Supplies Store',
      price: 'undefiend',
      Link: 'https://market.x-cart.com/ecommerce-templates/kitchen-supplies-store.html?backURL=https%3A%2F%2Fmarket.x-cart.com%2Fecommerce-templates%2F%23productid-4696',
      Description:
        "The Kitchen Supplies Store design template is good for stores selling accessories, kitchen supplies & furniture. It's bright and looks stylish and professional due to red and black colors combination. Clear fully responsive layout and convenient navigation, cloud zoom effect for product images and detailed images in pop-ups ensure best shopping experience for your store visitors. The template offers different options for your promotions, such as big banners on the top and on the bottom of the homepage and additional informational blocks in the footer. The template is SEO friendly and compatible with all popular browsers.",
      categorie: 'Fitness',
      versions: '5.0 - 5.3',
    },
    {
      img: 'https://market.x-cart.com/var/images/template_images/286.418/Skins_list_image_632x924_5_1.jpg',
      MainImg: 'https://market.x-cart.com/var/images/product/680.580/Skin_details_image_1360x1160px_3.jpg',
      LogoImg: 'https://market.x-cart.com/var/images/module_icons/120.60/iconAlt_294.png',
      head: 'Fireworks',
      price: 'undefiend',
      Link: 'https://market.x-cart.com/ecommerce-templates/fireworks.html?backURL=https%3A%2F%2Fmarket.x-cart.com%2Fecommerce-templates%2F%23productid-4550',
      Description:
        'This bright high-contrast skin with modern straight cornered flat design will become a good fit for stores selling fireworks and car accessories. A 100% wide homepage slideshow, custom subcategory blocks, a semi-transparent top bar and a top-aligned placeholder for category banners will attract your store visitors’ attention. Inset featured products, new arrivals, bestsellers product tabs will ergonomically fit your store pages. This template is fully-adapted to mobile devices, SEO-friendly and looks great in all popular browsers.',
      categorie: 'Entertainment',
      versions: '5.4',
    },
    {
      img: 'https://market.x-cart.com/var/images/template_images/286.418/MG_listing_286h418_2h.jpg',
      MainImg: 'https://market.x-cart.com/var/images/product/680.580/details_page_New-6.jpg',
      LogoImg: 'https://market.x-cart.com/var/images/module_icons/120.60/icon_22.png',
      head: 'Marble Grey',
      price: 'Free',
      Link: 'https://market.x-cart.com/ecommerce-templates/marble-grey.html?backURL=https%3A%2F%2Fmarket.x-cart.com%2Fecommerce-templates%2F%23productid-5160',
      Description: 'The light gray background and bright-colored key elements in this theme will focus your audience on the most important parts. This template is suitable for fashion & beauty stores, household goods, electronics, and sport. This template is 100% mobile ready, SEO optimized, and looks great in all popular browsers.',
      categorie: 'Apparel & Clothing',
      versions: '5.0 - 5.3',
    },
    {
      img: 'https://market.x-cart.com/var/images/template_images/286.418/Template_51_Ultimate_skin.jpg',
      MainImg: 'https://market.x-cart.com/var/images/product/680.580/Template_51_Ultimate_skin%20%281%29.jpg',
      LogoImg: 'https://market.x-cart.com/var/images/module_icons/120.60/iconAlt_256.png',
      head: 'Ultimate Skin',
      price: '149.00',
      Link: 'https://market.x-cart.com/ecommerce-templates/ultimate-skin.html?backURL=https%3A%2F%2Fmarket.x-cart.com%2Fecommerce-templates%2F%23productid-3941',
      Description:
        'The template designed in aegean and sky blue shades looks light and neat. Due to its simple clean design it can be used for various stores: accessories, clothing, fashion, jewelry, sport, wedding. Your store will look perfect on any device due to responsive full-width design. Built-in tools such as flyout menus and product carousel enhance navigation and make presentation of your products more attractive for your store visitors. It’s SEO friendly and optimized for all popular browsers.',
      categorie: 'Fitness',
      versions: '5.4',
    },
    {
      img: 'https://market.x-cart.com/var/images/template_images/286.418/Template_43_Alternative_Clothes.jpg',
      MainImg: 'https://market.x-cart.com/var/images/product/680.580/Skin_details_image_1360x1160px_3_19.jpg',
      LogoImg: 'https://market.x-cart.com/var/images/module_icons/120.60/iconAlt_43.png',
      head: 'Alternative clothes',
      price: '99.00',
      Link: 'https://market.x-cart.com/ecommerce-templates/alternative-clothes-for-v4.html?backURL=https%3A%2F%2Fmarket.x-cart.com%2Fecommerce-templates%2F%23productid-4799',
      Description:
        'If you are looking to build mysterious and extraordinary atmosphere in your store, consider this template in dark colors. It’s a perfect fit for stores selling unusual youth clothes, jewelry, accessories, and it will also work for music and watches. Your customers will appreciate convenience in navigation provided by this template and will come back to your store over and over again. Featured products, bestsellers, products on sale, new arrivals, etc are beautifully presented in carousels on the home page. Those who want to use X-Cart Banner system add-on will be glad to find out that the its design has been adapted to look nice with this template.',
      categorie: 'Apparel & Clothing',
      versions: '5.4',
    },
    {
      img: 'https://market.x-cart.com/var/images/template_images/286.418/Template_45_Intimates.jpg',
      MainImg: 'https://market.x-cart.com/var/images/product/680.580/Template_45_Intimates_1.jpg',
      LogoImg: 'https://market.x-cart.com/var/images/module_icons/120.60/iconAlt_47.png',
      head: 'Intimates',
      price: '99.00',
      Link: 'https://market.x-cart.com/ecommerce-templates/intimates.html?backURL=https%3A%2F%2Fmarket.x-cart.com%2Fecommerce-templates%2F%23productid-2905',
      Description:
        "This stylish theme with tender pink accents has been developed for Fashion, Clothes, Jewelry and Design stores. The template is SEO friendly, compatible with all popular browsers and mobile ready, it will look great on any screen. Big full-width banner in the top and additional banners in the bottom will grab your store visitors attention to your promotions and offers. Products on sale, featured products, new arrivals and bestsellers are beautifully presented in built-in carousels. The template comes with dropdown categories menu, one of the category featured products is displayed in this drop-down next to subcategories list. Products in minicart widget are shown in blocks with product name, price and image, and customers can remove products right from there which makes cart management more convenient for them. With adapted news on the homepage you can be confident that all your latest records won't go unnoticed.",
      categorie: 'Apparel & Clothing',
      versions: '4.5 - 4.9',
    },
    {
      img: 'https://market.x-cart.com/var/images/template_images/286.418/Template_48_Graphic_Stock_1.jpg',
      MainImg: 'https://market.x-cart.com/var/images/product/680.580/Template_48_Graphic_Stock_2.jpg',
      LogoImg: 'https://market.x-cart.com/var/images/module_icons/120.60/iconAlt_52.png',
      head: 'Graphics Stock',
      price: '149.00',
      Link: 'https://market.x-cart.com/ecommerce-templates/graphicstock.html?backURL=https%3A%2F%2Fmarket.x-cart.com%2Fecommerce-templates%2F%23productid-3128',
      Description: "The development of this add-on has been discontinued. It means that you can use it as is, but there will be no new features, bug-fixes, support of newer versions, etc. If you need this add-on to be adapted for your version of X-Cart, contact us at https://www.x-cart.com/custom-development.html. The 'Graphic Stock' X-Cart Design Template (#48). This template is good for the following themes: Graphics, cars, books, accessories, equipment",
      categorie: 'Art & Photography',
      versions: '4.0 - 4.4',
    },
    {
      img: 'https://market.x-cart.com/var/images/template_images/286.418/Template_37_Apple_Shop.jpg',
      MainImg: 'https://market.x-cart.com/var/images/product/680.580/Template_37_Apple_Shop_1.jpg',
      LogoImg: 'https://market.x-cart.com/var/images/module_icons/120.60/iconAlt_31.png',
      head: 'Apple Shop',
      price: '99.00',
      Link: 'https://market.x-cart.com/ecommerce-templates/apple-shop-for-v4.html?backURL=https%3A%2F%2Fmarket.x-cart.com%2Fecommerce-templates%2F%23productid-4803',
      Description: 'Are you going to sell computers, electronics, tools & equipment or business products? Then this template is right for you. It will bring contemporary and stylish look to your store due to clean ultrawhite design. Well thought layout ensures convenient navigation for your customers. Bestsellers are promoted right on the homepage and are beautifully presented in carousels.',
      categorie: 'Computer',
      versions: '4.5 - 4.9',
    },
    {
      img: 'https://market.x-cart.com/var/images/template_images/286.418/Skins_list_image_632x924_8_8.jpg',
      MainImg: 'https://market.x-cart.com/var/images/product/680.580/Skin_details_image_1360x1160px_3_9.jpg',
      LogoImg: 'https://market.x-cart.com/var/images/module_icons/120.60/icon_189.png',
      head: 'Linen',
      price: '149.00',
      Link: 'https://market.x-cart.com/ecommerce-templates/linen.html?backURL=https%3A%2F%2Fmarket.x-cart.com%2Fecommerce-templates%2F%23productid-4698',
      Description:
        'Make yourself at home! A bluish palette of the template renders the feel of peace and relaxation. Thus, the theme perfectly suits to create the atmosphere of comfort and home. We recommend using the theme for the bed linen goods and related items. The extensive top menu with the fixed position on scrolling and enlarged product images help to find a desired product in the catalog easily. The theme also provides information blocks with animated illustrations for the home page. Feel free to announce the sale running in the store or new collection arrived. This theme is fully responsive so it looks perfect on any device with any screen size the user has in hand while shopping.',
      categorie: 'Apparel & Clothing',
      versions: '4.0 - 4.4',
    },
  ],
};
