export const Data = {
  Free$Paid: ['Free & Paid', 'Free', 'Paid', 'Sale'],
  Compatible: [
    'All versions',
    '5.4',
    '5.3',
    '5.0 - 5.2',
    '4.7',
    '4.6',
    '4.5',
    '4.0 - 4.4',
  ],
  Categories: [
    'All Categories',
    'Apparel & Clothing',
    'Art & Photography',
    'Books',
    'Buisness',
    'Cars',
    'Computer',
    'Crafts and hobbies',
    'Education',
    'Electronics',
    'Entertainment',
    'Equipment and Tools',
    'Fitness',
    'Flower',
    'Food & Drink',
    'Furniture & Interior',
    'Gifts',
    'Health & Beauty',
    'Industrial',
    'Jewelry & Accessories',
  ],
  Contents: [
    {
      img: 'https://market.x-cart.com/var/images/template_images/286.418/Skins_list_image_632x924_8_7.jpg',
      head: 'Kitchen Supplies Store',
      price: '139.00',
      Link: 'https://market.x-cart.com/ecommerce-templates/kitchen-supplies-store.html?backURL=https%3A%2F%2Fmarket.x-cart.com%2Fecommerce-templates%2F%23productid-4696',
    },
    {
      img: 'https://market.x-cart.com/var/images/template_images/286.418/Skins_list_image_632x924_5_1.jpg',
      head: 'Fireworks',
      price: '139.00',
      Link: 'https://market.x-cart.com/ecommerce-templates/fireworks.html?backURL=https%3A%2F%2Fmarket.x-cart.com%2Fecommerce-templates%2F%23productid-4550',
    },
    {
      img: 'https://market.x-cart.com/var/images/template_images/286.418/MG_listing_286h418_2h.jpg',
      head: 'Marble Grey',
      price: 'Free',
      Link: 'https://market.x-cart.com/ecommerce-templates/marble-grey.html?backURL=https%3A%2F%2Fmarket.x-cart.com%2Fecommerce-templates%2F%23productid-5160',
    },
    {
      img: 'https://market.x-cart.com/var/images/template_images/286.418/Template_51_Ultimate_skin.jpg',
      head: 'Ultimate Skin',
      price: '149.00',
      Link: 'https://market.x-cart.com/ecommerce-templates/ultimate-skin.html?backURL=https%3A%2F%2Fmarket.x-cart.com%2Fecommerce-templates%2F%23productid-3941',
    },
    {
      img: 'https://market.x-cart.com/var/images/template_images/286.418/Template_43_Alternative_Clothes.jpg',
      head: 'Alternative clothes',
      price: '99.00',
      Link: 'https://market.x-cart.com/ecommerce-templates/alternative-clothes-for-v4.html?backURL=https%3A%2F%2Fmarket.x-cart.com%2Fecommerce-templates%2F%23productid-4799',
    },
    {
      img: 'https://market.x-cart.com/var/images/template_images/286.418/Template_45_Intimates.jpg',
      head: 'Intimates',
      price: '99.00',
      Link: 'https://market.x-cart.com/ecommerce-templates/intimates.html?backURL=https%3A%2F%2Fmarket.x-cart.com%2Fecommerce-templates%2F%23productid-2905',
    },
    {
      img: 'https://market.x-cart.com/var/images/template_images/286.418/Template_48_Graphic_Stock_1.jpg',
      head: 'Graphics Stock',
      price: '149.00',
      Link: 'https://market.x-cart.com/ecommerce-templates/graphicstock.html?backURL=https%3A%2F%2Fmarket.x-cart.com%2Fecommerce-templates%2F%23productid-3128',
    },
    {
      img: 'https://market.x-cart.com/var/images/template_images/286.418/Template_37_Apple_Shop.jpg',
      head: 'Apple Shop',
      price: '99.00',
      Link: 'https://market.x-cart.com/ecommerce-templates/apple-shop-for-v4.html?backURL=https%3A%2F%2Fmarket.x-cart.com%2Fecommerce-templates%2F%23productid-4803',
    },
    {
      img: 'https://market.x-cart.com/var/images/template_images/286.418/Skins_list_image_632x924_8_8.jpg',
      head: 'Linen',
      price: '149.00',
      Link: 'https://market.x-cart.com/ecommerce-templates/linen.html?backURL=https%3A%2F%2Fmarket.x-cart.com%2Fecommerce-templates%2F%23productid-4698',
    },
  ],
};
